/* eslint-disable global-require */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,md,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,md,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['input-sans', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'Noto Sans', 'sans-serif'],
        display: ['nickel-gothic-variable', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        'si-green': '#0e9b4a',
        'si-green-dark': '#0b5129',
        'si-gold-light': '#e6be31',
        'si-gold': '#d99a32',
        'si-gold-dark': '#9f622e',
        'cube-red': '#c4232c',
        'cube-orange': '#f57b20',
        'cube-green': '#00984c',
        'cube-blue': '#195dac',
        'cube-yellow': '#fdc117',
        'cube-white': '#dddedf',
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
  daisyui: {
    themes: [
      {
        speedcubing: {
          "primary": "#0e9b4a",
          "primary-content": "#ffffff",
          "secondary": "#d99a32",
          "secondary-content": "#000000",
          "accent": "#f57b20",
          "accent-content": "#000000",
          "neutral": "#0b5129",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f2f2f2",
          "base-300": "#dddedf",
          "base-content": "#1a1a1a",
          "info": "#195dac",
          "info-content": "#ffffff",
          "success": "#00984c",
          "success-content": "#ffffff",
          "warning": "#fdc117",
          "warning-content": "#000000",
          "error": "#c4232c",
          "error-content": "#ffffff",
        },
      },
      {
        "speedcubing-dark": {
          "primary": "#0e9b4a",
          "primary-content": "#ffffff",
          "secondary": "#e6be31",
          "secondary-content": "#000000",
          "accent": "#f57b20",
          "accent-content": "#000000",
          "neutral": "#1a1a1a",
          "neutral-content": "#dddedf",
          "base-100": "#000000",
          "base-200": "#141414",
          "base-300": "#1e1e1e",
          "base-content": "#dddedf",
          "info": "#195dac",
          "info-content": "#ffffff",
          "success": "#0e9b4a",
          "success-content": "#ffffff",
          "warning": "#e6be31",
          "warning-content": "#000000",
          "error": "#c4232c",
          "error-content": "#ffffff",
        },
      },
    ],
  },
};
